data:
  name: endovis17
  train_path: /bd_byta6000i0/users/surgicaldinov2/kyyang/sam2-video-training/data/endovis17_coco_annotations_train.json
  val_path: /bd_byta6000i0/users/surgicaldinov2/kyyang/sam2-video-training/data/endovis17_coco_annotations_val.json
  image_size: 512
  video_clip_length: 8
  stride: 8
  num_workers: 2
  batch_size: 1
  num_categories: 7
defaults:
- /data/endovis17@data
model:
  fintuned_model_path: /bd_byta6000i0/users/sam2/wl/zero_shot/sam_model_test/endovis17_bbox/endovis17_bbox_18.torch
  trainable_modules:
  - memory_encoder
  - memory_attention
  prompt_type: box
data_module:
  data: ${data}
