# Configuration for PyTorch Lightning trainer
accelerator: auto
devices: auto
precision: 16-mixed
max_epochs: 50
gradient_clip_val: 1.0
accumulate_grad_batches: 1
limit_train_batches: 1.0
limit_val_batches: 1.0
val_check_interval: 1.0
num_sanity_val_steps: 2
enable_checkpointing: true
enable_progress_bar: true
logger: true
log_every_n_steps: 20

# Early stopping (optional)
early_stopping_patience: null