dataset:
  batch_size: 1
  data_path: ''
  image_size: !!python/tuple
  - 512
  - 512
  include_center_point: false
  num_points: !!python/tuple
  - 1
  - 3
  num_workers: 16
  prompt_types:
  - point
  - bbox
  - mask
  shuffle: true
  video_clip_length: 5
log_level: INFO
loss:
  bce_weight: 1.0
  dice_weight: 1.0
  iou_weight: 0.5
  smooth: 1.0e-06
  temporal_weight: 0.1
model:
  add_tpos_enc_to_obj_ptrs: true
  backbone_stride: 16
  checkpoint_path: ''
  config_path: ''
  device: cuda
  image_size: 512
  max_obj_ptrs_in_encoder: 16
  multimask_output_for_tracking: true
  multimask_output_in_sam: true
  num_maskmem: 7
  proj_tpos_enc_in_obj_ptrs: true
  trainable_modules:
  - memory_attention
  - memory_encoder
  use_obj_ptrs_in_encoder: true
  use_signed_tpos_enc_to_obj_ptrs: true
optimizer:
  betas: !!python/tuple
  - 0.9
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  type: AdamW
  weight_decay: 0.0001
output_dir: ./outputs
save_dir: ./checkpoints
scheduler:
  T_max: 10
  enabled: true
  eta_min: 1.0e-06
  gamma: 0.1
  step_size: 5
  type: CosineAnnealingLR
seed: 42
trainer:
  accelerator: auto
  accumulate_grad_batches: 1
  devices: auto
  early_stopping_patience: null
  enable_checkpointing: true
  enable_progress_bar: true
  gradient_clip_val: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  logger: true
  max_epochs: 50
  num_sanity_val_steps: 2
  precision: 16-mixed
  val_check_interval: 1.0
use_wandb: true
wandb_project: sam2-training
