# @package _global_

defaults:
- /data/endovis17@data
model:
  fintuned_model_path: null
  trainable_modules:
  - memory_encoder
  - memory_attention
  prompt_type: point
combo:
  name: endovis17_point_mem
data_module:
  data: ${data}

