# @package _global_

defaults:
- /data/endovis17@data
model:
  fintuned_model_path: null
  trainable_modules:
  - mask_decoder
  - prompt_encoder
  prompt_type: point
combo:
  name: endovis17_point_md+pe
data_module:
  data: ${data}

