# @package _global_

defaults:
- /data/endovis17@data
model:
  fintuned_model_path: /bd_byta6000i0/users/sam2/wl/zero_shot/sam_model_test/endovis17_point/endovis17_point_3.torch
  trainable_modules:
  - mask_decoder
  - memory_encoder
  - memory_attention
  prompt_type: point
  num_pos_points: 1
combo:
  name: endovis17_1_mem_sfx
data_module:
  data: ${data}
