# @package _global_

defaults:
- /data/endovis17@data
model:
  fintuned_model_path: /bd_byta6000i0/users/sam2/wl/zero_shot/sam_model_test/endovis17_bbox_pe/endovis17_bbox_pe_12.torch
  trainable_modules:
  - memory_encoder
  - memory_attention
  prompt_type: box
combo:
  name: endovis17_5_mem
data_module:
  data: ${data}

