# @package _global_

defaults:
- /data/endovis17@data
model:
  fintuned_model_path: /bd_byta6000i0/users/sam2/wl/zero_shot/sam_model_test/endovis17_mask_pe/endovis17_mask_pe_17.torch
  trainable_modules:
  - memory_encoder
  - memory_attention
  - mask_decoder
  - prompt_encoder
  prompt_type: mask
data_module:
  data: ${data}

