# @package _global_

defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: null
  trainable_modules:
  - mask_decoder
  prompt_type: point
combo:
  name: cholecseg8k_point_md
data_module:
  data: ${data}

