# @package _global_

defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: null
  trainable_modules:
  - memory_encoder
  - memory_attention
  - mask_decoder
  - prompt_encoder
  - image_encoder
  prompt_type: point
combo:
  name: cholecseg8k_point_mem+md+pe+ie
data_module:
  data: ${data}
