# @package _global_

defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: null
  trainable_modules:
  - mask_decoder
  - prompt_encoder
  - image_encoder
  prompt_type: box
combo:
  name: cholecseg8k_box_md+pe+ie
data_module:
  data: ${data}

