# @package _global_

defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: /bd_byta6000i0/users/sam2/wl/zero_shot/sam_model_test/cholecseg8k_point_all/cholecseg8k_point_all_18.torch
  trainable_modules:
  - prompt_encoder
  - image_encoder
  - mask_decoder
  - memory_encoder
  - memory_attention
  prompt_type: point
  num_pos_points: 1
data_module:
  data: ${data}
