# @package _global_

defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: /bd_byta6000i0/users/sam2/wl/zero_shot/sam_model_test/cholecseg8k_point_pe/cholecseg8k_point_pe_10.torch
  trainable_modules:
  - memory_encoder
  - memory_attention
  prompt_type: point
  num_pos_points: 1
combo:
  name: cholecseg8k_3_mem
data_module:
  data: ${data}

