# @package _global_

defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: null
  trainable_modules:
  - memory_encoder
  - memory_attention
  prompt_type: box
combo:
  name: cholecseg8k_box_mem
data_module:
  data: ${data}

