# @package _global_

defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: /bd_byta6000i0/users/sam2/wl/zero_shot/sam_model_test/cholecseg8k_bbox_pe/cholecseg8k_bbox_pe_15.torch
  trainable_modules:
  - mask_decoder
  - prompt_encoder
  prompt_type: box
data_module:
  data: ${data}

