# @package _global_

defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: /bd_byta6000i0/users/sam2/wl/zero_shot/sam_model_test/cholecseg8k_bbox_all/cholecseg8k_bbox_all_8.torch
  trainable_modules:
  - memory_encoder
  - memory_attention
  prompt_type: box
combo:
  name: cholecseg8k_6_mem
data_module:
  data: ${data}

