# @package _global_

defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: null
  trainable_modules:
  - memory_encoder
  - memory_attention
  - mask_decoder
  prompt_type: mask
combo:
  name: cholecseg8k_mask_mem+md
data_module:
  data: ${data}
