defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: null
  trainable_modules:
  - memory_encoder
  - memory_attention
  - mask_decoder
  prompt_type: point
  num_pos_points: 1
combo:
  name: cholecseg8k_raw_point
data_module:
  data: ${data}

