defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: null
  trainable_modules:
  - memory_encoder
  - memory_attention
  - mask_decoder
  prompt_type: mask
  num_pos_points: 1
data_module:
  data: ${data}

