# @package _global_

defaults:
- /data/endovis18@data
model:
  fintuned_model_path: null
  trainable_modules:
  - mask_decoder
  - prompt_encoder
  prompt_type: box
combo:
  name: endovis18_box_md+pe
data_module:
  data: ${data}

