# @package _global_

defaults:
- /data/endovis18@data
model:
  fintuned_model_path: null
  trainable_modules:
  - memory_encoder
  - memory_attention
  - mask_decoder
  - prompt_encoder
  - image_encoder
  prompt_type: mask
combo:
  name: endovis18_mask_mem+md+pe+ie
data_module:
  data: ${data}
