wandb_version: 1

optimizer.eps:
  value: 1.0e-06
optimizer.lr:
  value: 3.0689484898657973e-05
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 0.5
