wandb_version: 1

optimizer.eps:
  value: 1.0e-07
optimizer.lr:
  value: 2.449815855546946e-06
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 4
trainer.gradient_clip_val:
  value: 0.1
