wandb_version: 1

optimizer.eps:
  value: 1.0e-05
optimizer.lr:
  value: 0.0002242011810473924
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 5
