wandb_version: 1

optimizer.eps:
  value: 1.0e-05
optimizer.lr:
  value: 1.6477068408090117e-06
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 0.1
