wandb_version: 1

optimizer.eps:
  value: 1.0e-05
optimizer.lr:
  value: 0.000840201032528979
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 32
trainer.gradient_clip_val:
  value: 0.5
