wandb_version: 1

optimizer.eps:
  value: 1.0e-08
optimizer.lr:
  value: 0.0005769349741541161
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 64
trainer.gradient_clip_val:
  value: 5
