wandb_version: 1

optimizer.eps:
  value: 1.0e-08
optimizer.lr:
  value: 6.313774255687371e-05
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 4
trainer.gradient_clip_val:
  value: 0.1
