wandb_version: 1

optimizer.eps:
  value: 1.0e-05
optimizer.lr:
  value: 1.6270175314420274e-05
optimizer.weight_decay:
  value: 0.1
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 10
