wandb_version: 1

optimizer.eps:
  value: 1.0e-06
optimizer.lr:
  value: 7.637798889852504e-06
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 16
trainer.gradient_clip_val:
  value: 10
