wandb_version: 1

optimizer.eps:
  value: 1.0e-06
optimizer.lr:
  value: 2.3208102553376255e-06
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 4
trainer.gradient_clip_val:
  value: 0.5
