wandb_version: 1

optimizer.eps:
  value: 1.0e-05
optimizer.lr:
  value: 0.001979200955903415
optimizer.weight_decay:
  value: 0.1
trainer.accumulate_grad_batches:
  value: 16
trainer.gradient_clip_val:
  value: 10
