wandb_version: 1

optimizer.eps:
  value: 1.0e-08
optimizer.lr:
  value: 3.2640447985787754e-05
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 16
trainer.gradient_clip_val:
  value: 1
