wandb_version: 1

optimizer.eps:
  value: 1.0e-05
optimizer.lr:
  value: 0.0003980309625617036
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 4
trainer.gradient_clip_val:
  value: 0.5
