wandb_version: 1

optimizer.eps:
  value: 1.0e-06
optimizer.lr:
  value: 4.747734574115275e-05
optimizer.weight_decay:
  value: 0.1
trainer.accumulate_grad_batches:
  value: 32
trainer.gradient_clip_val:
  value: 5
