wandb_version: 1

optimizer.eps:
  value: 1.0e-06
optimizer.lr:
  value: 0.0033745725032805203
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 4
trainer.gradient_clip_val:
  value: 1
