wandb_version: 1

optimizer.eps:
  value: 1.0e-06
optimizer.lr:
  value: 3.5048710843313744e-06
optimizer.weight_decay:
  value: 0.1
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 1
