wandb_version: 1

optimizer.eps:
  value: 1.0e-07
optimizer.lr:
  value: 1.2433819418000896e-06
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 16
trainer.gradient_clip_val:
  value: 1
