wandb_version: 1

optimizer.eps:
  value: 1.0e-06
optimizer.lr:
  value: 0.001169043964465438
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 0.5
