wandb_version: 1

optimizer.eps:
  value: 1.0e-07
optimizer.lr:
  value: 0.00013987004888428616
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 16
trainer.gradient_clip_val:
  value: 5
