wandb_version: 1

optimizer.eps:
  value: 1.0e-08
optimizer.lr:
  value: 4.99542623891059e-06
optimizer.weight_decay:
  value: 0.1
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 5
