wandb_version: 1

optimizer.eps:
  value: 1.0e-07
optimizer.lr:
  value: 8.822399176230515e-05
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 1
