wandb_version: 1

optimizer.eps:
  value: 1.0e-07
optimizer.lr:
  value: 7.887988531266952e-06
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 0.1
