wandb_version: 1

optimizer.eps:
  value: 1.0e-08
optimizer.lr:
  value: 6.5379174412812105e-06
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 1
