wandb_version: 1

optimizer.eps:
  value: 1.0e-07
optimizer.lr:
  value: 0.0030375905272000715
optimizer.weight_decay:
  value: 0.1
trainer.accumulate_grad_batches:
  value: 32
trainer.gradient_clip_val:
  value: 0.5
