wandb_version: 1

optimizer.eps:
  value: 1.0e-06
optimizer.lr:
  value: 0.006377591396652145
optimizer.weight_decay:
  value: 0.1
trainer.accumulate_grad_batches:
  value: 16
trainer.gradient_clip_val:
  value: 5
