wandb_version: 1

optimizer.eps:
  value: 1.0e-08
optimizer.lr:
  value: 0.00028902379201642864
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 10
