wandb_version: 1

optimizer.eps:
  value: 1.0e-06
optimizer.lr:
  value: 6.65271402150279e-05
optimizer.weight_decay:
  value: 0.01
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 1
