wandb_version: 1

optimizer.eps:
  value: 1.0e-08
optimizer.lr:
  value: 8.743766688269342e-06
optimizer.weight_decay:
  value: 0.1
trainer.accumulate_grad_batches:
  value: 4
trainer.gradient_clip_val:
  value: 5
