wandb_version: 1

optimizer.eps:
  value: 1.0e-06
optimizer.lr:
  value: 1.7362699600496743e-06
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 64
trainer.gradient_clip_val:
  value: 0.1
