wandb_version: 1

optimizer.eps:
  value: 1.0e-05
optimizer.lr:
  value: 9.475278266091052e-05
optimizer.weight_decay:
  value: 0.001
trainer.accumulate_grad_batches:
  value: 64
trainer.gradient_clip_val:
  value: 0.5
