wandb_version: 1

optimizer.eps:
  value: 5.007879268558211e-09
optimizer.lr:
  value: 0.003177945762269244
optimizer.weight_decay:
  value: 0.0011224678774791395
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 10
