wandb_version: 1

optimizer.eps:
  value: 2.318788681262805e-07
optimizer.lr:
  value: 0.004477183267745379
optimizer.weight_decay:
  value: 5.3544112612307964e-08
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 10
