wandb_version: 1

optimizer.eps:
  value: 0.0002798908523144719
optimizer.lr:
  value: 0.0001031632672574316
optimizer.weight_decay:
  value: 2.869193814638595e-07
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 5
