wandb_version: 1

optimizer.eps:
  value: 2.8399744114473645e-08
optimizer.lr:
  value: 0.002778247446504492
optimizer.weight_decay:
  value: 1.1355788879214658e-08
trainer.accumulate_grad_batches:
  value: 32
trainer.gradient_clip_val:
  value: 10
