wandb_version: 1

optimizer.eps:
  value: 7.103566160843097e-07
optimizer.lr:
  value: 7.869171143728548e-06
optimizer.weight_decay:
  value: 0.009978449063103191
trainer.accumulate_grad_batches:
  value: 64
trainer.gradient_clip_val:
  value: 5
