wandb_version: 1

optimizer.eps:
  value: 0.0001694770276578982
optimizer.lr:
  value: 1.51495914204309e-05
optimizer.weight_decay:
  value: 1.2798024110559458e-07
trainer.accumulate_grad_batches:
  value: 16
trainer.gradient_clip_val:
  value: 5
