wandb_version: 1

optimizer.eps:
  value: 0.0036513232791344848
optimizer.lr:
  value: 1.83232758581039e-06
optimizer.weight_decay:
  value: 0.0004218149862080518
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 10
