wandb_version: 1

optimizer.eps:
  value: 7.806320537097838e-05
optimizer.lr:
  value: 0.003873275982262862
optimizer.weight_decay:
  value: 2.205551920729278e-05
trainer.accumulate_grad_batches:
  value: 32
trainer.gradient_clip_val:
  value: 10
