wandb_version: 1

optimizer.eps:
  value: 1.1688492446453585e-07
optimizer.lr:
  value: 9.039482502598097e-06
optimizer.weight_decay:
  value: 3.4847033732980604e-07
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 0.1
