wandb_version: 1

optimizer.eps:
  value: 1.3461910322391555e-06
optimizer.lr:
  value: 0.0003571017914300237
optimizer.weight_decay:
  value: 5.651203817817344e-08
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 5
