wandb_version: 1

optimizer.eps:
  value: 8.191609872497907e-08
optimizer.lr:
  value: 0.009178115213771716
optimizer.weight_decay:
  value: 1.0362504986770638e-08
trainer.accumulate_grad_batches:
  value: 16
trainer.gradient_clip_val:
  value: 1
