wandb_version: 1

optimizer.eps:
  value: 1.04063090037531e-07
optimizer.lr:
  value: 3.84633802642356e-05
optimizer.weight_decay:
  value: 3.0702347672121526e-05
trainer.accumulate_grad_batches:
  value: 4
trainer.gradient_clip_val:
  value: 0.1
