wandb_version: 1

optimizer.eps:
  value: 0.000120995626033625
optimizer.lr:
  value: 8.949193527471072e-06
optimizer.weight_decay:
  value: 8.128817815297633e-09
trainer.accumulate_grad_batches:
  value: 32
trainer.gradient_clip_val:
  value: 0.5
