wandb_version: 1

optimizer.eps:
  value: 7.208887148925602e-09
optimizer.lr:
  value: 2.556602700334021e-05
optimizer.weight_decay:
  value: 0.00044535190929176
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 5
