wandb_version: 1

optimizer.eps:
  value: 4.592725282346557e-06
optimizer.lr:
  value: 0.000725870525798887
optimizer.weight_decay:
  value: 0.0010526675034938204
trainer.accumulate_grad_batches:
  value: 32
trainer.gradient_clip_val:
  value: 5
