wandb_version: 1

optimizer.eps:
  value: 2.2830372193406886e-07
optimizer.lr:
  value: 0.001654797004656824
optimizer.weight_decay:
  value: 7.424037323654516e-07
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 1
