wandb_version: 1

optimizer.eps:
  value: 4.912614074923237e-06
optimizer.lr:
  value: 7.195839879414791e-05
optimizer.weight_decay:
  value: 3.329184246133969e-07
trainer.accumulate_grad_batches:
  value: 16
trainer.gradient_clip_val:
  value: 0.5
