wandb_version: 1

optimizer.eps:
  value: 0.0014838867097729412
optimizer.lr:
  value: 1.234443608313242e-05
optimizer.weight_decay:
  value: 4.256011833894159e-09
trainer.accumulate_grad_batches:
  value: 4
trainer.gradient_clip_val:
  value: 0.1
