wandb_version: 1

optimizer.eps:
  value: 0.0006961408747628203
optimizer.lr:
  value: 5.163557740370909e-05
optimizer.weight_decay:
  value: 3.0335638153544096e-08
trainer.accumulate_grad_batches:
  value: 16
trainer.gradient_clip_val:
  value: 0.1
