wandb_version: 1

optimizer.eps:
  value: 3.083347074560795e-05
optimizer.lr:
  value: 0.003473959766188448
optimizer.weight_decay:
  value: 1.3249998729636394e-09
trainer.accumulate_grad_batches:
  value: 32
trainer.gradient_clip_val:
  value: 5
