wandb_version: 1

optimizer.eps:
  value: 1.7934769384445698e-05
optimizer.lr:
  value: 0.0001778758805138983
optimizer.weight_decay:
  value: 2.900508636096503e-08
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 0.5
