wandb_version: 1

optimizer.eps:
  value: 0.000733034631870381
optimizer.lr:
  value: 0.001380561910166883
optimizer.weight_decay:
  value: 1.3568906973232256e-07
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 10
