wandb_version: 1

optimizer.eps:
  value: 1.8732619798756993e-06
optimizer.lr:
  value: 6.983034009474383e-05
optimizer.weight_decay:
  value: 6.624365151912298e-09
trainer.accumulate_grad_batches:
  value: 4
trainer.gradient_clip_val:
  value: 0.1
