wandb_version: 1

optimizer.eps:
  value: 0.00018191231941639736
optimizer.lr:
  value: 1.212127115299726e-06
optimizer.weight_decay:
  value: 7.830949647914674e-08
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 5
