wandb_version: 1

optimizer.eps:
  value: 7.682345737945675e-09
optimizer.lr:
  value: 4.4516427662387974e-06
optimizer.weight_decay:
  value: 1.0225705497891e-07
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 10
