wandb_version: 1

optimizer.eps:
  value: 6.674777921974966e-08
optimizer.lr:
  value: 1.763564676631971e-06
optimizer.weight_decay:
  value: 2.0756098197827998e-08
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 0.5
