wandb_version: 1

optimizer.eps:
  value: 0.003320649198768593
optimizer.lr:
  value: 1.959169278010691e-05
optimizer.weight_decay:
  value: 1.3278802944477462e-06
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 0.1
