wandb_version: 1

optimizer.eps:
  value: 0.0005890044808007134
optimizer.lr:
  value: 1.8001138473978512e-05
optimizer.weight_decay:
  value: 7.21579164985745e-07
trainer.accumulate_grad_batches:
  value: 32
trainer.gradient_clip_val:
  value: 5
