wandb_version: 1

optimizer.eps:
  value: 0.0005079019274399053
optimizer.lr:
  value: 1.4579461964798472e-05
optimizer.weight_decay:
  value: 4.521247061890485e-09
trainer.accumulate_grad_batches:
  value: 32
trainer.gradient_clip_val:
  value: 10
