wandb_version: 1

optimizer.eps:
  value: 2.6503704748518958e-09
optimizer.lr:
  value: 0.0001491788872280867
optimizer.weight_decay:
  value: 0.000239387118408032
trainer.accumulate_grad_batches:
  value: 4
trainer.gradient_clip_val:
  value: 5
