wandb_version: 1

optimizer.eps:
  value: 8.00188784773783e-09
optimizer.lr:
  value: 1.7387703598331996e-05
optimizer.weight_decay:
  value: 1.021408926243243e-07
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 1
