wandb_version: 1

optimizer.eps:
  value: 1.4785257266677822e-07
optimizer.lr:
  value: 0.0006328325115279516
optimizer.weight_decay:
  value: 2.326201514791517e-08
trainer.accumulate_grad_batches:
  value: 64
trainer.gradient_clip_val:
  value: 0.5
