wandb_version: 1

optimizer.eps:
  value: 9.076917284751713e-08
optimizer.lr:
  value: 3.5461349423587622e-06
optimizer.weight_decay:
  value: 1.2606800717067557e-06
trainer.accumulate_grad_batches:
  value: 1
trainer.gradient_clip_val:
  value: 10
