wandb_version: 1

optimizer.eps:
  value: 1.084607265982818e-07
optimizer.lr:
  value: 1.4540439978388276e-05
optimizer.weight_decay:
  value: 3.539692402251128e-05
trainer.accumulate_grad_batches:
  value: 8
trainer.gradient_clip_val:
  value: 10
