# Configuration for SAM2 model
checkpoint_path: ""
config_path: configs/sam2.1_hiera_t.yaml
trainable_modules:
  - memory_attention
  - memory_encoder
device: cuda

# Tracker parameters
num_maskmem: 7
image_size: 512
backbone_stride: 16
use_obj_ptrs_in_encoder: true
max_obj_ptrs_in_encoder: 16
add_tpos_enc_to_obj_ptrs: true
proj_tpos_enc_in_obj_ptrs: true
use_signed_tpos_enc_to_obj_ptrs: true
multimask_output_in_sam: true
multimask_output_for_tracking: true
max_objects: 10