# Configuration for dataset
dataset_type: coco
data_path: /bd_byta6000i0/users/surgicaldinov2/kyyang/sam2/cholecseg8k/coco_style/merged_gt_coco_annotations_train.json
image_size: [512, 512]
video_clip_length: 5
batch_size: 1
num_workers: 16
shuffle: true

# Prompt configuration
prompt_types: ["point"]
num_of_pos_points: 1
num_of_neg_points: 0
include_center_point: true