defaults:
  - model: sam2
  - data: coco
  - loss: default
  - optimizer: adamw
  - scheduler: cosine
  - trainer: default
  - swanlab: default
  - visualization: default
  - _self_

# Global settings
seed: 42
use_wandb: true
wandb_project: sam2-video-training
output_dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Logging
log_level: INFO

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}