defaults:
  - config
  - _self_

model:
  trainable_modules:
    - mask_decoder
    - memory_encoder
    - memory_attention
  

trainer:
  max_epochs: 50
  limit_train_batches: 1
  limit_val_batches: 1
  val_check_interval: null
  num_sanity_val_steps: 1
  detect_anomaly: false
  log_every_n_steps: 1
  gradient_clip_val: 3
  accumulate_grad_batches: 1
  precision: 16

scheduler:
  enabled: false
  warmup_enabled: false

optimizer:
  type: AdamW
  lr: 7e-3
  weight_decay: 1e-4
  betas: [0.9, 0.98]
  eps: 1e-5
  amsgrad: true
  warmup_factor: 0.1

visualization:
  train_every_n_steps: 1

data:
  video_clip_length: 8
  stride: 20

loss:
  type: raw