defaults:
  - config
  - _self_

model:
  trainable_modules:
    - mask_decoder
  

trainer:
  limit_train_batches: 2
  limit_val_batches: 1
  val_check_interval: null
  num_sanity_val_steps: 1
  log_every_n_steps: 1
  gradient_clip_val: 0.1
  detect_anomaly: true

optimizer:
  lr: 1e-4

visualization:
  train_every_n_steps: 1

data:
  video_clip_length: 8
  stride: 20

loss:
  type: bce