data:
  name: cholecseg8k
  train_path: /bd_byta6000i0/users/surgicaldinov2/kyyang/sam2-video-training/data/cholecseg8k_coco_annotations_train_opened.json
  val_path: /bd_byta6000i0/users/surgicaldinov2/kyyang/sam2-video-training/data/cholecseg8k_coco_annotations_val_opened.json
  image_size: 512
  video_clip_length: 8
  stride: 8
  num_workers: 2
  batch_size: 1
  num_categories: 13
defaults:
- /data/cholecseg8k@data
model:
  fintuned_model_path: /bd_byta6000i0/users/sam2/wl/zero_shot/sam_model_test/cholecseg8k_point_pe/cholecseg8k_point_pe_10.torch
  trainable_modules:
  - memory_encoder
  - memory_attention
  prompt_type: point
  num_pos_points: 1
data_module:
  data: ${data}
